Controllers/MenuController.cs
using UltimoApps.DAL;
using UltimoApps.DAL.Membership;
using UltimoApps.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace UltimoApps.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Menu/

        //public ActionResult Index(string Id)
        //{
        //    var objDataAccess = new DAL.Repository();
        //    var Result = objDataAccess.GetMenuById(Id);
        //    return View(Result);
        //}
        //public ActionResult Error(string Id)
        //{
        //    return HttpNotFound("403");
        //}

        public ActionResult GetAllMenuForm(string url)
        {
            if (Sc_RolePermission.IsHasPermission("btn_edit", url))
            {
                var serializer = new JavaScriptSerializer();
                var serializedResult = serializer.Serialize(Sc_Menu.getAllMenuFormData("", "", 0, 1000));

                return Json(serializedResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { error = Global.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetAllMenuFormByRoleID(string url, string roleId)
        {
            if (Sc_RolePermission.IsHasPermission("btn_edit", url))
            {
                var serializer = new JavaScriptSerializer();
                var serializedResult = serializer.Serialize(Sc_Menu.GetAllMenuFormDataByRoleID(roleId));

                return Json(serializedResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { error = Global.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult GetAllMenuFormData(string filter, string searchKey, int skip, int take, string url)
        {
            if (Sc_RolePermission.IsHasPermission("btn_search", url))
            {
                try
                {
                    MenuBindingModel result = new MenuBindingModel { Data = Sc_Menu.getAllMenuFormData(filter, searchKey, skip, take), Total = Sc_Menu.GetAllMenuFormDataTotal(filter, searchKey) };
                    var serializer = new JavaScriptSerializer();
                    var serializedResult = serializer.Serialize(result);

                    return Json(serializedResult, JsonRequestBehavior.AllowGet);
                }
                catch
                {
                    return Json(new { error = Global.ErrorMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { error = Global.AccessMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult getAllParentMenu()
        {
            try
            {
                var serializer = new JavaScriptSerializer();
                var serializedResult = serializer.Serialize(Sc_Menu.getAllParentMenu());

                return Json(serializedResult, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { error = Global.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult updateMenuForm(Compact_MenuFormModel model, string url)
        {
            if (Sc_RolePermission.IsHasPermission("btn_edit", url))
            {
                try
                {
                    if (Sc_Menu.UpdateFromCompactModel(model))
                    {
                        return Json(new { success = Global.InsertMessage }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { error = "Update Error : " + Global.ErrorMessage }, JsonRequestBehavior.AllowGet);
                    }
                }
                catch (Exception ex)
                {
                    return Json(new { error = ex.Message + " : " + ex.InnerException }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { error = "Update Error : " + Global.AccessMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult newMenuForm(Compact_MenuFormModel model, string url)
        {
            if (Sc_RolePermission.IsHasPermission("btn_create", url))
            {
                if (Sc_Menu.insertCompactModel(model))
                {
                    return Json(new { success = Global.InsertMessage }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { error = "Update Error : Inserted data not valid" }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { error = "Update Error : " + Global.AccessMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult deleteMenuForm(string id, string url)
        {
            if (Sc_RolePermission.IsHasPermission("btn_delete", url))
            {
                try
                {
                    if (Sc_MenuForm.delete(id))
                    {
                        return Json(new { success = "success" }, JsonRequestBehavior.AllowGet);
                    }
                    else {
                        return Json(new { error = Global.ErrorMessage }, JsonRequestBehavior.AllowGet);
                    }
                }
                catch
                {
                    return Json(new { error = Global.ErrorMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { error = "Update Error : " + Global.AccessMessage }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

Views/Partials/Partial_DataEntry_Rejection.cshtml
@model UltimoApps.DAL.tbRejectedTran

<div class="modal fade" id="modal-reject-detail">

    <div class="modal-dialog modal-lg" role="document">

        <div class="modal-content">

            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                    <span aria-hidden="true">&times;</span>

                    <span class="sr-only">Close</span>

                </button>

                <h4 class="modal-title uppercase">MANAGE REJECT QUANTITY</h4>

            </div>
            <div class="modal-body clearfix">
                <div class="col-sm-12" style="background-color: #120b4c">
                    <div class="row">
                        @Html.HiddenFor(model => model._rejid, new { @id = "hfrid" })
                        @Html.HiddenFor(model => model._refID, new { @id = "hfRefID" })
                        <div class="col-sm-6" style="color:#dcdecd">
                            <div class="col-sm-6">
                                @Html.Label("infoReceivedQTY", "RECEIVED QTY :", new { @class = "control-label" })
                            </div>
                            <div class="col-sm-6">
                                @Html.Label("txtRejReceivedQTY", "_", new { @id = "txtRejReceivedQty" })
                            </div>
                        </div>
                        <div class="col-sm-6" style="color:#dcdecd">
                            <div class="col-sm-6">
                                @Html.Label("infoCompeledQTY", "COMPLETED QTY :", new { @class = "control-label" })
                            </div>
                            <div class="col-sm-6">
                                @Html.Label("txtRejCompQty", "_", new { @id = "txtRejCompQty" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6" style="color:#dcdecd">
                            <div class="col-sm-6">
                                @Html.Label("infoRejectedQTY", "REJECTED QTY :", new { @class = "control-label" })
                            </div>
                            <div class="col-sm-6">
                                @Html.Label("txtRejRejectedQty", "_", new { @id = "txtRejRejectedQty" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12" style="background-color: #C5C7CA">
                    <div class="row" style="margin-top:12px">
                        <div class="col-sm-6">
                            <div class="col-sm-6">
                                @Html.Label("infoRejectedCode", "REJECTED CODE :", new { @class = "control-label" })
                            </div>
                            <div class="col-sm-6">
                                @Html.TextBoxFor(model => model._RejectedCode, new { @id = "cmbRejCode", @style = "width:100%;", @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="col-sm-6">
                                @Html.Label("infoRejectedQTY", "REJECTED QTY :", new { @class = "control-label" })
                            </div>
                            <div class="col-sm-6">
                                @Html.TextBoxFor(model => model._RejectedQty, new { @id = "txtRejQty", @style = "width:100%;", @class = "form-control", @type = "number" })
                            </div>
                        </div>
                    </div>
                    <div class="row" style="padding-bottom: 10px;">
                        <div class="col-sm-10">
                            <div class="col-sm-3">
                                @Html.Label("infoRejectedDesc", "DESCRIPTION :", new { @class = "control-label" })
                            </div>
                            <div class="col-sm-8" style="width: 100%;">
                                @Html.TextAreaFor(model => model._RejectedDesc, new { @id = "txtRejDesc", @style = "width:100%;", @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <button type="button" id="btnRejAdd" class="btn btn-success btn-block" name="command" value="addReject" style="margin-top:20px">Add</button>
                            <button type="button" id="btnRejRemove" class="btn btn-danger btn-block" name="command" value="removeReject" >Remove</button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div id="grid-rejected-detail" class="grid-rejected"></div>
                    </div>
                </div>
                <div class="row" style="margin-top:12px">
                    <div class="col-sm-2">
                        <button type="button" class="btn btn-block" data-dismiss="modal" aria-label="Close">Close</button>
                        <button type="button" id="btnRejCancel" class="btn btn-block btn-danger">Cancel</button>
                    </div>
                    <div class="col-sm-4"></div>
                    <div class="col-sm-6">
                        @Html.Label("infoRejQty", "TOTAL REJECTED QTY :", new { @class = "control-label" })
                        @Html.Label("txtRejTotalQty", "T :", new { @id = "txtRejTotalQty", @class = "label-total-reject  control-label" })
                    </div>
                </div>


            </div>
            <!-- /.modal-content -->

        </div>

        <!-- /.modal-dialog -->

    </div>

    <!-- /.modal -->
</div>

Views/Partials/Partial_JobDetails.cshtml
@model UltimoApps.Models.JobDetailModel

@using UltimoApps.DAL

@{ 
    var tempURL = Request.FilePath;
    var currentURL = tempURL.Substring(1, tempURL.Length - 1);
}
<div class="modal fade" id="modal-form-update">

    <div class="modal-dialog modal-lg" role="document">

        <div class="modal-content">

            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                    <span aria-hidden="true">&times;</span>

                    <span class="sr-only">Close</span>

                </button>

                <h4 class="modal-title uppercase">Job Details</h4>

            </div>



            @using (Ajax.BeginForm("DetailsJob", "JobOrder", new { url = Request.RawUrl.Replace("/", "") }, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "divResult", OnBegin = "ViewBegin", OnFailure = "ViewError", OnSuccess = "ViewSuccess" }, new { @class = "form-horizontal" }))
            {
                        
                <div class="modal-body clearfix">
                    @Html.HiddenFor(model => model._job, new { @id = "hf-list-menu-update" })
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label">Job No :</label>
                                <div class="col-sm-4">
                                    @Html.TextBoxFor(model => model._job, new { @class = "form-control", @readonly = "readonly", @id = "PartxtJobNo" })
                                    @*@Html.ValidationMessageFor(model => model._job)*@
                                </div>
                                <label for="" class="col-sm-2 control-label">Item :</label>
                                <div class="col-sm-4">
                                    @Html.TextBoxFor(model => model._item, new { @class = "form-control", @readonly = "readonly", @id = "PartxtItem" })
                                    @*@Html.ValidationMessageFor(model => model._jobsuffix)*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label">Suffix :</label>
                                <div class="col-sm-4">
                                   @Html.TextBoxFor(model => model._jobsuffix, new { @class = "form-control", @readonly = "readonly", @id = "PartxtSuffix" })
                                    @*@Html.ValidationMessageFor(model => model._qtyReleased)*@
                                </div>
                                <label for="" class="col-sm-2 control-label">Qty Released :</label>
                                <div class="col-sm-4">
                                    @Html.TextBoxFor(model => model._qtyReleased, new { @class = "form-control", @readonly = "readonly", @id = "PartxtReleased" })
                                    @*@Html.ValidationMessageFor(model => model._wc)*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label">Date :</label>
                                <div class="col-sm-4">
                                    @Html.TextBoxFor(model => model._jobDate, new { @class = "form-control", @readonly = "readonly", @id = "PartxtDate" })
                                    @*@Html.ValidationMessageFor(model => model._wc)*@
                                </div>
                                <label for="" class="col-sm-2 control-label">Qty Completed :</label>
                                <div class="col-sm-4">
                                    @Html.TextBoxFor(model => model._qtyCompleted, new { @class = "form-control", @readonly = "readonly", @id = "PartxtCompleted" })
                                    @*@Html.ValidationMessageFor(model => model._wc)*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label" style="margin-left: 450px">Qty Scrapped :</label>
                                <div class="col-sm-4">
                                    @Html.TextBoxFor(model => model._qtyScrapped, new { @class = "form-control", @readonly = "readonly", @id = "PartxtScrapped" })
                                    @*@Html.ValidationMessageFor(model => model._wc)*@
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div id="grid-menu-update"></div>
                    </div>
                </div>
                <div class="modal-footer" >
                    <div class="col-sm-12 text-right">
                        <button type="submit" class="btn bg-black uppercase" data-dismiss="modal" aria-label="Close" style="margin-right: 800px">close</button>
                        <button id="btnUpdate" type="submit" class="btn btn-success uppercase" style="display:none;">Save</button>
                    </div>
                </div>
                
            }



            <!-- /.modal-content -->

        </div>

        <!-- /.modal-dialog -->

    </div>

    <!-- /.modal -->
</div>

Views/Partials/Partial_Menu_Edit.cshtml
@model UltimoApps.Models.Compact_MenuFormModel
@using UltimoApps.DAL

@{
    var tempURL = Request.FilePath;
    var currentURL = tempURL.Substring(1, tempURL.Length - 1);
}

<div class="modal fade" id="modal-form">

    <div class="modal-dialog modal-lg" role="document">

        <div class="modal-content">

            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                    <span aria-hidden="true">&times;</span>

                    <span class="sr-only">Close</span>

                </button>

                <h4 class="modal-title uppercase">EDIT MENU</h4>

            </div>



            @{                    
                if (Sc_RolePermission.IsHasPermission("btn_edit", currentURL))
                {
                    using (Ajax.BeginForm("updateMenuForm", "Menu", new { url = Request.RawUrl.Replace("/", "") }, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "divResult", OnBegin = "ViewBegin", OnFailure = "ViewError", OnSuccess = "ViewSuccess" }, new { @class = "form-horizontal" }))
                    {
                @Html.HiddenFor(model => model.ListForm)
                @Html.ValidationSummary(true);
                <div class="modal-body">
                    <div class="row">
                        @*top field*@
                        <div class="col-sm-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.MenuID, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.MenuID, new { @class = "form-control", @readonly = "readonly" })
                                    @Html.ValidationMessageFor(model => model.MenuID)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Menu, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.Menu, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Menu)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MenuDesc, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">

                                    @Html.TextBoxFor(model => model.MenuDesc, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MenuDesc)
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ParentID, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.ParentID, new { @class = "form-control txtParentID", @id = "txtParentID" })
                                    @Html.ValidationMessageFor(model => model.ParentID)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MenuURL, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.MenuURL, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MenuURL)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.HiddenFor(model => model.IsActive, new { @value = true })
                                @Html.LabelFor(model => model.IsActive, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    <i id="status-is-active" class="btn-change-active fa"></i>
                                </div>
                            </div>
                             <div class="form-group">
                                @Html.HiddenFor(model => model.IsHide, new { @value = false, @id="IsHideUpdate" })
                                @Html.LabelFor(model => model.IsHide, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    <i id="hide-is-active-update" class="btn-hide-change-active-update fa"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-20 border pt-10">
                        @*Form kiri*@
                        <div class="col-md-5">
                            <div id="menu-form-grid"></div>
                        </div>
                        @*button swap table*@
                        <div class="col-md-2 border-left border-right">
                            <button type="button" name="button" class="btn btn-default btn-block" id="to-left"><< </button>
                            <button type="button" name="button" class="btn btn-default btn-block" id="to-right">>> </button>
                        </div>
                        @*button kanan*@
                        <div class="col-sm-5">
                            <div id="all-form-grid"></div>
                        </div>

                        <div id="form-grid"></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-sm-12 text-right">
                            <button type="submit" class="btn bg-black uppercase" data-dismiss="modal" aria-label="Close">close</button>
                            <button id="btnSave" type="submit" class="btn btn-success uppercase">Save</button>
                        </div>
                    </div>
                </div>             
                    }
                }
                else
                {
                <p>@Global.AccessMessage</p>
                }
            }
        </div>
        <!-- /.modal-content -->

    </div>
    <!-- /.modal-dialog -->

</div>
<!-- /.modal -->

<div class="modal fade" id="modal-form-new">

    <div class="modal-dialog modal-lg" role="document">

        <div class="modal-content">

            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                    <span aria-hidden="true">&times;</span>

                    <span class="sr-only">Close</span>

                </button>

                <h4 class="modal-title uppercase">NEW MENU</h4>

            </div>



            @{    
                if (Sc_RolePermission.IsHasPermission("btn_create", currentURL))
                {
                    using (Ajax.BeginForm("newMenuForm", "Menu", new { url = Request.RawUrl.Replace("/", "") }, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "divResult", OnBegin = "ViewBegin", OnFailure = "ViewError", OnSuccess = "ViewSuccess" }, new { @class = "form-horizontal" }))
                    {
                @Html.ValidationSummary(true);
                @Html.HiddenFor(Model => Model.ListForm, new { @id="ListForm-new"})
                <div class="modal-body">
                    <div class="row">
                        @*top field*@
                        <div class="col-sm-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.MenuID, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.MenuID, new { @class = "form-control" , @id="MenuID-new"})
                                    @Html.ValidationMessageFor(model => model.MenuID)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Menu, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.Menu, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Menu)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MenuDesc, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">

                                    @Html.TextBoxFor(model => model.MenuDesc, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MenuDesc)
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ParentID, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.ParentID, new { @class = "form-control txtParentID", @id = "txtParentID-new" })
                                    @Html.ValidationMessageFor(model => model.ParentID)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MenuLvl, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    @{
                                             var selectItem = new List<SelectListItem>();
                                             selectItem.Add(new SelectListItem { Value = "1", Text = "1" });
                                             selectItem.Add(new SelectListItem { Value = "2", Text = "2" });
                                             selectItem.Add(new SelectListItem { Value = "3", Text = "3" });
                                    }
                                    @Html.DropDownListFor(model => model.MenuLvl, selectItem, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MenuLvl)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MenuURL, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.MenuURL, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MenuURL)
                                </div>
                            </div>
                            
                             <div class="form-group">
                                @Html.HiddenFor(model => model.IsHide, new { @value = false })
                                @Html.LabelFor(model => model.IsHide, new { @class = "col-sm-4 control-label" })
                                <div class="col-sm-8">
                                    <i id="hide-is-active" class="btn-hide-change-active fa"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-20 border pt-10">

                        @*Form kiri*@
                        <div class="col-sm-5">
                            <div id="menu-form-grid-new"></div>
                        </div>
                        @*button swap table*@
                            <div class="col-md-2 border-left border-right">
                                <button type="button" name="button" class="btn btn-default btn-block" id="to-left-new"><< </button>
                                <button type="button" name="button" class="btn btn-default btn-block" id="to-right-new">>> </button>
                            </div>
                        @*button kanan*@
                        <div class="col-sm-5">
                            <div id="all-form-grid-new"></div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-sm-12 text-right">
                            <button type="submit" class="btn bg-black uppercase" data-dismiss="modal" aria-label="Close">close</button>
                            <button id="btnSave-new" type="submit" class="btn btn-success uppercase">Save</button>
                        </div>
                    </div>
                </div>                 
                    }
                }
                else
                {
                <p>@Global.AccessMessage</p>
                }
            }

        </div>
        <!-- /.modal-content -->

    </div>
    <!-- /.modal-dialog -->

</div>
<!-- /.modal -->